Initialize project
werkraum-media/form_file_collection pull request #1
Opened 2023-06-28 06:48 UTC by DanielSiepmann

Provide first implementation with basic setup.

2023-06-28 16:36 UTC, justusmoroni requested changes

2023-06-28 16:36 UTC, justusmoroni commented on Classes/Form/FormElement/FileCollectionElement.php
> +     * @return array<string, string>
```suggestion

     * @return array<string, string>
```

It's like this in line 76-78.

2023-06-28 16:36 UTC, justusmoroni commented on README.rst
> +That allows for using existing templates that allow to select one or multiple options.
Sounds weird. Maybe:

```suggestion
That allows usage of existing templates that already handle one or multiple options.
```

2023-06-28 16:36 UTC, justusmoroni commented on Tests/Functional/FormIntegrationTest.php
> +            'fluid_styled_content',
Is this used? We don't require it in the test extension.

2023-06-28 16:36 UTC, justusmoroni commented on phpunit.xml.dist
> +    >
```suggestion
>
```

2023-06-29 05:15 UTC, DanielSiepmann commented on Tests/Functional/FormIntegrationTest.php
> +            'fluid_styled_content',
We do, we render the content, and we would not have any rendering definition for CType `list`, that's provided by `fluid_styled_content`.

2023-06-29 05:31 UTC, DanielSiepmann commented on Classes/Form/FormElement/FileCollectionElement.php
> +     * @return array<string, string>
Added cs fixer rule and applied it.

2023-07-03 07:52 UTC, justusmoroni approved these changes

2023-07-03 08:08 UTC, merged